# Simple MED Spell Corrector

### 0.References

http://www.hakank.org/reading_scrambled_words/g_spell.cgi

https://careerkarma.com/blog/python-sort-a-dictionary-by-value/

https://www.geeksforgeeks.org/python-get-the-first-key-in-dictionary/

https://www.geeksforgeeks.org/python-remove-punctuation-from-string/

In [151]:
real_sentence = "Key point analysis is the task of extracting a set of concise and high-level statements from a given collection of arguments, representing the gist of these arguments."
test_sentence = "Kxy oint analyuis ie he taskv o etracting a est orf concisme nd highh-leveml tsatements form a givn colection f arguemnts, rpresenting hte ist fo htese agruments."

### 1.Imports

In [152]:
import numpy as np
import re
import copy

### 2.Read Dataset

In [153]:
# read dataset function
def read_data_set(in_dir):
    f = open(in_dir, "r", encoding="utf-8")
    lines = f.readlines()
    new_lines = []
    for line in lines:
        if line.endswith("\n"):
            new_lines.append(line[:-1]) # delete the \n at the end of each line
        else:
            new_lines.append(line)
    return new_lines

In [154]:
words = read_data_set("Vocabulary (for Bonus section).txt")

In [155]:
print(len(words))

61336


### 3.Edit Distance function

In [156]:
def edit_distance_calculator(a, b, log=False):
    len_a = len(a)
    len_b = len(b)
    distance_matrix = np.zeros((len_a+1,len_b+1))
    
    # Init step
    for i in range(len(distance_matrix)):
        distance_matrix[i,0]=i
        
    for j in range(len(distance_matrix[0])):
        distance_matrix[0,j]=j
        
    # Recursion Relation
    for i in range(1,len(distance_matrix)):
        for j in range(1,len(distance_matrix[0])):
            replace_distance = 0 if a[i-1]==b[j-1] else 2
            distance_matrix[i,j] = min(distance_matrix[i-1,j]+1, distance_matrix[i,j-1]+1, distance_matrix[i-1,j-1]+replace_distance)
            
    if log:
        print(distance_matrix)
    return int(distance_matrix[-1][-1])

In [157]:
# Test if log==True: it prints the distance matrix
print(edit_distance_calculator("terain", "terrain",log=True))

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [1. 0. 1. 2. 3. 4. 5. 6.]
 [2. 1. 0. 1. 2. 3. 4. 5.]
 [3. 2. 1. 0. 1. 2. 3. 4.]
 [4. 3. 2. 1. 2. 1. 2. 3.]
 [5. 4. 3. 2. 3. 2. 1. 2.]
 [6. 5. 4. 3. 4. 3. 2. 1.]]
1


In [158]:
print(edit_distance_calculator("aslkmk", "immilk",log=False))

8


### 4.Edit Distance dictionary for each word

In [159]:
def distances_dictionary_calculator(word, words):
    distances_dictionary = {}
    for i in range(len(words)):
        distances_dictionary[words[i]]=edit_distance_calculator(words[i], word)
        
    return distances_dictionary

In [160]:
sample_distances_dictionary = distances_dictionary_calculator("point", words)

In [161]:
# Check some samples
print(sample_distances_dictionary["point"])
print(sample_distances_dictionary["po"])
print(sample_distances_dictionary["join"])
print(sample_distances_dictionary["joint"])

0
3
3
2


### 5.Dictionary sorting by distance

In [162]:
def dictionary_sorter(dictionary):
    sorted_dictionary = dict(sorted(dictionary.items(), key=lambda x: x[1], reverse=False))
    return sorted_dictionary

In [163]:
sorted_sample_distances_dictionary = dictionary_sorter(sample_distances_dictionary)

In [164]:
sorted_sample_distances_dictionary

{'point': 0,
 'pint': 1,
 'points': 1,
 'appoint': 2,
 'joint': 2,
 'paint': 2,
 'pin': 2,
 'pints': 2,
 'pit': 2,
 'pointed': 2,
 'pointer': 2,
 'posit': 2,
 'pot': 2,
 'print': 2,
 'anoint': 3,
 'appoints': 3,
 'coin': 3,
 'dint': 3,
 'endpoint': 3,
 'font': 3,
 'forint': 3,
 'hint': 3,
 'in': 3,
 'into': 3,
 'it': 3,
 'join': 3,
 'joints': 3,
 'lint': 3,
 'loin': 3,
 'midpoint': 3,
 'mint': 3,
 'omit': 3,
 'on': 3,
 'onto': 3,
 'orient': 3,
 'outpoint': 3,
 'pain': 3,
 'paints': 3,
 'pant': 3,
 'pent': 3,
 'pi': 3,
 'pine': 3,
 'ping': 3,
 'pink': 3,
 'pinpoint': 3,
 'pins': 3,
 'pith': 3,
 'pits': 3,
 'pitt': 3,
 'pity': 3,
 'plaint': 3,
 'pliant': 3,
 'plinth': 3,
 'plot': 3,
 'po': 3,
 'poet': 3,
 'poignant': 3,
 'pointers': 3,
 'pointing': 3,
 'poison': 3,
 'poking': 3,
 'polite': 3,
 'pond': 3,
 'pony': 3,
 'poplin': 3,
 'poring': 3,
 'port': 3,
 'posing': 3,
 'post': 3,
 'potent': 3,
 'potion': 3,
 'pots': 3,
 'pout': 3,
 'prints': 3,
 'profit': 3,
 'pronto': 3,
 'punt': 3,
 '

### 6.Keeping the words within desired ED range

In [165]:
def dictionary_cutoff(dictionary, max_ed=2):
    cutted_dictionary = copy.deepcopy(dictionary)
    for key, value in dictionary.items():
        if value > max_ed:
            del cutted_dictionary[key]
            
    return cutted_dictionary

In [166]:
cutted_sorted_sample_distances_dictionary = dictionary_cutoff(sorted_sample_distances_dictionary, max_ed=2)

In [167]:
cutted_sorted_sample_distances_dictionary

{'point': 0,
 'pint': 1,
 'points': 1,
 'appoint': 2,
 'joint': 2,
 'paint': 2,
 'pin': 2,
 'pints': 2,
 'pit': 2,
 'pointed': 2,
 'pointer': 2,
 'posit': 2,
 'pot': 2,
 'print': 2}

### 7.Get the first key in dictionary as the most similar word

In [168]:
def first_key_getter(dictionary):
    return list(dictionary.keys())[0]

In [169]:
first_key_getter(cutted_sorted_sample_distances_dictionary)

'point'

### 8.Simple tokenizer + lowercase + preprocessor

In [209]:
def simple_tokenizer_lowercase(sentence):
    sentence = re.sub('-', ' ', sentence)
    sentence = re.sub('[^\w\s]', '', sentence)

    sentence_lower = sentence.lower()
    return sentence_lower.split()

In [210]:
simple_tokenizer_lowercase(test_sentence)

['kxy',
 'oint',
 'analyuis',
 'ie',
 'he',
 'taskv',
 'o',
 'etracting',
 'a',
 'est',
 'orf',
 'concisme',
 'nd',
 'highh',
 'leveml',
 'tsatements',
 'form',
 'a',
 'givn',
 'colection',
 'f',
 'arguemnts',
 'rpresenting',
 'hte',
 'ist',
 'fo',
 'htese',
 'agruments']

### 9.Putting it all together

In [211]:
def word_spell_corrector(word, max_ed=2, words=words):
    distances_dictionary = distances_dictionary_calculator(word, words)
    sorted_distances_dictionary = dictionary_sorter(distances_dictionary)
    cutted_sorted_distances_dictionary = dictionary_cutoff(sorted_distances_dictionary, max_ed=max_ed)
    return cutted_sorted_distances_dictionary

def sentence_spell_corrector(sentence, max_ed=2, words=words):
    tokens = simple_tokenizer_lowercase(sentence)
    best_tokens = []
    spell_dictionaries = []
    for token in tokens:
        print(f"Token {token} is being processed.")
        cutted_sorted_distances_dictionary = word_spell_corrector(word=token, max_ed=max_ed, words=words)
        best_tokens.append(first_key_getter(cutted_sorted_distances_dictionary))
        spell_dictionaries.append(cutted_sorted_distances_dictionary)
        
    print("Dictionaries generation finished.")  
      
    return best_tokens, spell_dictionaries, tokens


def result_viewer(sentence, max_ed=2, words=words):
    best_tokens, spell_dictionaries, tokens = sentence_spell_corrector(sentence, max_ed=max_ed, words=words)
    corrected_sentence = " ".join(best_tokens)
    for i in range(len(tokens)):
        print("The main token is: ", tokens[i])
        print("The best match is: ", best_tokens[i])
        print("The suggestions dictioary within the ED range is: ",spell_dictionaries[i])
        
    print("Sentence with all the best matches is: ",corrected_sentence)

In [212]:
result_viewer(test_sentence, max_ed=2, words=words)

Token kxy is being processed.
Token oint is being processed.
Token analyuis is being processed.
Token ie is being processed.
Token he is being processed.
Token taskv is being processed.
Token o is being processed.
Token etracting is being processed.
Token a is being processed.
Token est is being processed.
Token orf is being processed.
Token concisme is being processed.
Token nd is being processed.
Token highh is being processed.
Token leveml is being processed.
Token tsatements is being processed.
Token form is being processed.
Token a is being processed.
Token givn is being processed.
Token colection is being processed.
Token f is being processed.
Token arguemnts is being processed.
Token rpresenting is being processed.
Token hte is being processed.
Token ist is being processed.
Token fo is being processed.
Token htese is being processed.
Token agruments is being processed.
Dictionaries generation finished.
The main token is:  kxy
The best match is:  k
The suggestions dictioary withi

In [213]:
print(real_sentence)

Key point analysis is the task of extracting a set of concise and high-level statements from a given collection of arguments, representing the gist of these arguments.


#### We can improve the performance by applying some rules for suggestions length and ordering. Which is not done here and is for future works!